apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-websecure-internal
spec:
  type: ClusterIP
  ports:
    - port: 8444
      targetPort: 8444
      protocol: TCP
      name: secure-internal
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }}